# Generated by Django 4.2.1 on 2023-05-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zip_code',
            new_name='zipcode',
        ),
    ]
